### ISSUE TITLE
ModuleNotFoundError: No module named 'detector'

### ISSUE THREAD

**Issue by RCpengnan** [MVIG-SJTU/AlphaPose#828]
![image](https://user-images.githubusercontent.com/74439931/110766774-7ed93e00-8290-11eb-83b0-524a63867c40.png)
Hello,I have downloaded the latest version, but I am running into this problem again.Can you tell me how to solve it!Thank you!

**Comment by RCpengnan** [comment]
I have installed pytorch1.1.0

**Comment by wmj142326** [comment]
I also meet the same problem!!

**Comment by hayoyo12** [comment]
I just remove the pycocotools line from the setup.py and build.
After that, do pip install pycocotools and then run the demo_reference.py!

**Comment by gcrluo** [comment]
i also meet the problem,don't know how to solve

**Comment by RCpengnan** [comment]
> i also meet the problem,don't know how to solve

setup.py and build ,will solve

**Comment by xiangwentao666** [comment]
What did you do to solve the problem? I... I've spent a lot of time on it..

**Comment by xiangwentao666** [comment]
> > i also meet the problem,don't know how to solve
> 
> setup.py and build ,will solve

But it didn't work for me .....OMG

**Comment by xiangwentao666** [comment]
> > > > i also meet the problem,don't know how to solve
> > > 
> > > 
> > > setup.py and build ,will solve
> > 
> > 
> > But it didn't work for me .....OMG Though I've installed the module named as "detector", it still raised the same exception: ModuleNotFoundError: No module named 'detector'
> 
> Have you solved this problem? I have this problem now.

nope.....not yet....
God.....

**Comment by xiangwentao666** [comment]
Recently, it raised exception like this:
**python 3.7.13
pyyaml==5.2
scipy==1.1.0
torch==1.2.0 torchvision==0.4.0
pillow==6.2.2**
`/root/miniconda3/envs/myconda/compiler_compat/ld: cannot find -lcudart
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1`

**Python 3.6.13
torch-1.1.0-cp36-cp36m-linux_x86_64.whl
torchvision-0.3.0-cp36-cp36m-manylinux1_x86_64.whl：**
`/root/miniconda3/envs/alphapose/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:12:22: fatal error: cusparse.h: No such file or directory
compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1`

Woo....HELP!

**Comment by andy1213aa** [comment]
> > > > > i also meet the problem,don't know how to solve
> > > > 
> > > > 
> > > > setup.py and build ,will solve
> > > 
> > > 
> > > But it didn't work for me .....OMG Though I've installed the module named as "detector", it still raised the same exception: ModuleNotFoundError: No module named 'detector'
> > 
> > 
> > Have you solved this problem? I have this problem now.
> 
> nope.....not yet.... God.....

I notice that there did exist the folder "detector" in the previous level of the folder "scripts" , so I simply copied the folder "detector" into folder "scripts" and sovle this error. This error also occures in the folders "alphapose" and "trackers". For my case it was solved in the same way.

Note that some paths will still be based on the folders before copying. (For example, the path of the yolov3 weight)

All in all, this inelegant way helped me solve the problem. If you're still stuck on this error and don't want to modify any code, you can give it a try!

**Comment by xiangwentao666** [comment]
> > > > > > i also meet the problem,don't know how to solve
> > > > > 
> > > > > 
> > > > > setup.py and build ,will solve
> > > > 
> > > > 
> > > > But it didn't work for me .....OMG Though I've installed the module named as "detector", it still raised the same exception: ModuleNotFoundError: No module named 'detector'
> > > 
> > > 
> > > Have you solved this problem? I have this problem now.
> > 
> > 
> > nope.....not yet.... God.....
> 
> I notice that there did exist the folder "detector" in the previous level of the folder "scripts" , so I simply copied the folder "detector" into folder "scripts" and sovle this error. This error also occures in the folders "alphapose" and "trackers". For my case it was solved in the same way.
> 
> Note that some paths will still be based on the folders before copying. (For example, the path of the yolov3 weight)
> 
> All in all, this inelegant way helped me solve the problem. If you're still stuck on this error and don't want to modify any code, you can give it a try!


Well, I've found something that may work for us. I inserted a few lines into the file "demo_inference.py", and finally it solved my problem. 
**Though problems been solved, I still cannot find out why this happened, because the folders named "detector", "alphapose" and "trackers" indeed exist in my project and the paths to them are actually correct.**

The new lines inserted are as follows:
`PROJECT_ROOT_PATH = ""`
`import sys`
`sys.path.append(PROJECT_ROOT_PATH)`

The variable PROJECT_ROOT_PATH mentioned above contains the path to the project folder. For example, the PROJECT_ROOT_PATH in my source code is 

"E:\Data\AlphaPose-master"

and then the path to the file "demo_inference.py" can be like this: 
`PROJECT_ROOT_PATH + "\" + "scripts\demo_inference.py"`
or
`"E:\Data\AlphaPose-master\scripts\demo_inference.py"`

As for the approach that simply copying the folder "detector" into folder "scripts", I think it is really not an appropriate one to solve problems of the same kind in the future. As for my resolution, I think it may be a temporal one as well...... Still waiting for more answers!

**Comment by 4lparslan** [comment]
Just move demo_inference.py to the main project path

**Comment by xiangwentao666** [comment]
> Just move demo_inference.py to the main project path


Thank you for your answer~

**Comment by skxmxm** [comment]
> 

That really worked. Thanks!

**Comment by skxmxm** [comment]
> Just move demo_inference.py to the main project path

That really worked. Thanks!!
